### ISSUE TITLE
IPT listed but not indexing by GloBI, present configuration correct?

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/lacm-lacmec#1]
@jhpoelen I noticed that for LACM the present IPT address is:
http://ipt.vertnet.org:8080/ipt/resource.do?r=lacm_ento

But the link to the archive version is:
http://ipt.vertnet.org:8080/ipt/archive.do?r=lacm_ento&v=5.4

Does the globi.json need to be configured directly to the .zip file? Or is the present configuration correct?

```
{
  "format": "dwca",
  "citation": "Natural History Museum of Los Angeles County",
  "url": "http://ipt.vertnet.org:8080/ipt/resource.do?r=lacm_ento"
}
```

When performing the review using elton/generate-report.sh I get this error associated with the collection. Perhaps this is useful information:

creating review [globalbioticinteractions/lacm-lacmec]... org.eol.globi.data.StudyImporterException: failed to read archive [https://github.com/globalbioticinteractions/lacm-lacmec/archive/216b0e456b1974cdc52b455a403346db9b6fe875.zip]
	at org.eol.globi.data.DatasetImporterForDwCA.importStudy(DatasetImporterForDwCA.java:202)
	at org.eol.globi.util.DatasetImportUtil.importDataset(DatasetImportUtil.java:65)
	at org.globalbioticinteractions.elton.cmd.CmdReview.review(CmdReview.java:154)
	at org.globalbioticinteractions.elton.cmd.CmdReview.reviewCachedOrRemote(CmdReview.java:116)
	at org.globalbioticinteractions.elton.cmd.CmdReview.run(CmdReview.java:107)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:15)
	at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:24)
	at org.globalbioticinteractions.elton.Elton.main(Elton.java:15)
Caused by: java.io.IOException: failed to read [file:/var/folders/f5/3g3m9l7s1qb6jync48jwg_c00000gn/T/dwca15806223113564775130tmp.zip]
	at org.globalbioticinteractions.dataset.DwCAUtil.archiveFor(DwCAUtil.java:29)
	at org.eol.globi.data.DatasetImporterForDwCA.importStudy(DatasetImporterForDwCA.java:175)
	... 7 more
Caused by: org.gbif.dwc.UnsupportedArchiveException: Parts of DwC-A are missing
	at org.gbif.dwc.Archive.validate(Archive.java:157)
	at org.gbif.dwc.DwcFiles.fromCompressed(DwcFiles.java:75)
	at org.globalbioticinteractions.dataset.DwCAUtil.archiveFor(DwCAUtil.java:24)
	... 8 more

**Comment by seltmann** [comment]
Upon looking at the Bee Library, the data provided does not include associations and is largely only skeletal records (scientific name). @seltmann check with data provider regarding plan for serving association data.

**Comment by jhpoelen** [comment]
@seltmann Just updated the ipt url to point to the dwca instead. thanks for catching this.

**Comment by seltmann** [comment]
great! thanks!
